trainer:
  model_name: distilbert-base-uncased
  dataset_name: ag_news
  num_labels: 4
  max_length: 256
  num_train_epochs: 2
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  learning_rate: 5e-5
  weight_decay: 0.01
  logging_steps: 50
  save_steps: 100
  eval_steps: 200
