# Experiment configuration for HF image captioning fine-tuning job

resources:
  nodes: 1
  gpus_per_node: 1
  gpu_type: "a40"
  time_limit: "0:10:00"

job_name: "hf-vlm-caption-single"
max_requeue: 2
job_dir: "~/vec_jobs"

trainer_kwargs:
  lr: 1e-5
  batch_size: 16
  num_epochs: 2
  print_every: 50
