defaults:
  - _global  # Import global config settings
  - _self_  # Must include the settings from this file

trainer:
  model_name: Salesforce/blip-image-captioning-base
  dataset_name: cifar10
  num_epochs: 2
  batch_size: 16
  learning_rate: 1e-5
  print_every: 50
  seed: 42

hydra:
  job:
    name: hydra_img-captioner
  searchpath:
    - pkg://configs  # Include configs from the configs package in the searchpath
