defaults:
  - user
  - compute: killarney/l40s_1x
  - requeue: "off"
  - _self_
  - override hydra/launcher: submitit_slurm

experiment_name: ${now:%Y%m%d}-${now:%H%M%S}

paths:
  work_root: ${oc.select:compute.work_root, /scratch/${oc.env:USER}}
  work_dir: ${paths.work_root}/vec_jobs/${experiment_name}

hydra:
  output_subdir: hydra_configs
  run:
    dir: ${paths.work_dir}
  sweep:
    dir: ${paths.work_dir}
  launcher:
    submitit_folder: ${hydra.sweep.dir}/submitit_logs/%j
    nodes: ${oc.select:compute.nodes,null}
    gpus_per_node: ${oc.select:compute.slurm.gpus_per_node, ${compute.gpus_per_node}}
    tasks_per_node: ${oc.select:compute.tasks_per_node, ${compute.gpus_per_node}}
    cpus_per_task: ${compute.cpus_per_task}
    mem_gb: ${compute.mem_gb}
    timeout_min: ${compute.timeout_min}
    gres: ${oc.select:compute.gres,null}
    partition: ${oc.select:compute.slurm.partition,null}
    qos: ${oc.select:compute.slurm.qos,null}
    account: ${user.slurm.account}
    max_num_timeout: 2
    additional_parameters: ${oc.select:user.slurm.additional_parameters, {}}
