cluster: bon_echo
nodes: 1
gpu_type: a40
gpus_per_node: 2
time_limit: "8:00:00"
timeout_min: 480
work_root: /scratch/ssd004/scratch/${oc.env:USER}
cpus_per_task: 8
mem_gb: 80
gres: gpu:${.gpu_type}:${.gpus_per_node}
slurm:
  partition: a40
  gpus_per_node: null
