cluster: bon_echo
nodes: 1
gpus_per_node: 0
gres: null
cpus_per_task: 2
mem_gb: 8 # values are binary GiB as expected by Slurm
work_root: /scratch/ssd004/scratch/${oc.env:USER}
timeout_min: 60
slurm:
  additional_parameters: {}
