cluster: killarney
nodes: 1
gpu_type: h100
gpus_per_node: 4
gres: gpu:${.gpu_type}:${.gpus_per_node}
tasks_per_node: ${.gpus_per_node}
cpus_per_task: 6
mem_gb: 960
work_root: /scratch/${oc.env:USER}
timeout_min: 60
slurm:
  additional_parameters: {}
