cluster: killarney
nodes: 1
gpu_type: h100
gpus_per_node: 1
time_limit: "1:00:00"
timeout_min: 60
work_root: /scratch/${oc.env:USER}
mem_gb: 256
cpus_per_task: 24
gres: gpu:${.gpu_type}:${.gpus_per_node}
slurm:
  gpus_per_node: null
