cluster: killarney
nodes: 1
gpu_type: l40s
gpus_per_node: 4
gres: gpu:${.gpu_type}:${.gpus_per_node}
tasks_per_node: ${.gpus_per_node}
cpus_per_task: 16
mem_gb: 480 # values are binary GiB as expected by Slurm
work_root: /scratch/${oc.env:USER}
timeout_min: 60
slurm:
  additional_parameters: {}
