cluster: killarney
nodes: 1
gpu_type: l40s
gpus_per_node: 1
gres: gpu:${.gpu_type}:${.gpus_per_node}
tasks_per_node: ${.gpus_per_node}
cpus_per_task: 16
mem_gb: 120
work_root: /scratch/${oc.env:USER}
timeout_min: 60
slurm:
  gpus_per_node: null
