cluster: killarney
nodes: 1
gpu_type: l40s
gpus_per_node: 4
time_limit: "1:00:00"
timeout_min: 60
work_root: /scratch/${oc.env:USER}
cpus_per_task: 16
mem_gb: 512
gres: gpu:${.gpu_type}:${.gpus_per_node}
slurm:
  gpus_per_node: null
