# Experiment configuration for HF text classification fine-tuning parameters sweep

# Job resource configuration
resources:
  nodes: 1
  gpus_per_node: 1
  gpu_type: "a40"
  time_limit: "0:10:00"

# Job metadata
job_name: "hf-textcls-sweep"
max_requeue: 2
job_dir: "~/vec_jobs"

# Base trainer arguments
trainer_kwargs:
  print_every: 50
  eval_steps: 200

# Parameter sweep space
sweep:
  lr: [5e-5, 1e-4]
  batch_size: [16]
  num_epochs: [1]
  save_steps: [100]
