# configs/user.yaml
# Every researcher MUST fill in their own account here.

slurm:
  account: AIP-XXXX   # <-- replace with your Alliance/Vector project account
  partition: gpu
  qos: normal

# Optionally override defaults
# defaults:
#   - override starter: llm_text_classification
#   - override compute: killarney/h100_1x
